name: Check for Secrets

on: [push]

jobs:

  detect_secrets:
    runs-on: ubuntu-latest
    name: detects the secrets

    steps:
      - name: run detect secrets
        uses: evanextreme/detect-secrets-action@v1.0.0