name: Check for Secrets

on: [push]

jobs:

  detect_secrets:
  
    runs-on: ubuntu-latest
    name: detect secrets

    steps:
    - uses: actions/checkout@v2
    - uses: UnicornGlobal/trufflehog-actions-scan@master
      with:
        branch: ${{ github.head_ref }}